### ISSUE TITLE
Error while starting download

### ISSUE THREAD

**Issue by tsvetowntopalov** [superafroman/node-torrent#26]
Uncaught node.js Error 

RangeError: Port should be > 0 and < 65536
    at connect (net.js:843:13)
    at net.js:940:9
    at dns.js:82:18
    at process._tickCallback (node.js:382:11)

**Comment by pepjo** [comment]
I've got a similar one: 

````
RangeError: Port should be > 0 and < 65536
    at Socket.send (dgram.js:278:11)
    at Object.UDP._send (D:\Pep\Projectes\torrents\node_modules\node-torrent\lib\tracker\udp.js:154:17)
    at Object.UDP._connect (D:\Pep\Projectes\torrents\node_modules\node-torrent\lib\tracker\udp.js:105:10)
    at Object.UDP.handle (D:\Pep\Projectes\torrents\node_modules\node-torrent\lib\tracker\udp.js:54:10)
    at Tracker._announce (D:\Pep\Projectes\torrents\node_modules\node-torrent\lib\tracker\tracker.js:61:13)
    at Tracker.start (D:\Pep\Projectes\torrents\node_modules\node-torrent\lib\tracker\tracker.js:39:8)
    at D:\Pep\Projectes\torrents\node_modules\node-torrent\lib\torrent\torrent.js:77:13
    at Array.forEach (native)
    at Torrent.start (D:\Pep\Projectes\torrents\node_modules\node-torrent\lib\torrent\torrent.js:76:17)
    at Torrent.<anonymous> (D:\Pep\Projectes\torrents\node_modules\node-torrent\lib\client.js:61:13)
````

**Comment by LinusU** [comment]
Which version of Node.js are you running?

**Comment by pepjo** [comment]
v4.2.1 isn't it supported?

**Comment by dmgd** [comment]
What's the tracker uri that's causing you the problemo?

**Comment by RaxoCoding** [comment]
hey i have the same issue with this: magnet:?xt=urn:btih:01113C30AE81430C4582CF76BDD2F5EDB37E1C95&dn=Rick.and.Morty.S01E01.720p.HDTV.x264-2HD+%5BPublicHD%5D&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.publichd.eu%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.istole.it%3A80&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.yify-torrents.com%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
